docs(additionalHeaders): allow additional headers to be sent with the…
wzr1337/rsi.schema pull request #9
Opened 2018-12-04 08:55 UTC by wzr1337

Let additional headers being sent with the request.

This feature is meant to allow sending transient information with the request which are not covered by standard headers of HTTP (WebSocket is ignored as it shall not contain transient information).

Image a feature like vehicle remote control where you want to start the engine or unlock the car. You might want to hand a secret - like a PIN or password - with the request in addition to the Authorization token to allow the control operation. You might generally have the authorization, but legal or security requirements force you to check a secret.

The following example uses the secret "superSecurePassword":
```http
POST /remoteaccess/vehicles/9f9079b2-9383-4ee4-b627-cca0e8444b08 HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.Ge22Vs5mGdCDjebNl-jMLGzc93tegVpfumHGNqPfO6s
X-Secret: superSecurePassword

{
  "lockState": "unlocked"
}
```

the schema file would hold the following section for elememnt level POST:

```json
...,
"additonalHeaders": {
  "X-Secret": {
    "isRequired": true,
    "type": "string"
  }
},
...
```

2018-12-04 17:15 UTC, ghost approved these changes

2018-12-06 21:09 UTC, sen542 commented
Does not convince me. If X-Secrets is an additional infomration it can also be encoded in the encrypted authorization token. 
Another question is the about the intention of the "additionaHeaders" element in the scheme. Presumably  it defines additional headers to be sent with hat request type. Where is the explantion of the intention? 
(From definition point of view the proposal is agreed but for from purpose/intention point of view. Do you have any other examples/use cases?

2018-12-06 21:12 UTC, sen542 commented
Does not convince me. If X-Secrets is an additional information it can also be encoded in the encrypted authorization token. 
Another question is the about the intention of the "additionaHeaders" element in the scheme. Presumably  it defines additional headers to be sent with hat request type. Where is the explantion of the intention? 
(From definition point of view the proposal is agreed but for from purpose/intention point of view. ) Have you got any other examples/use cases?

2018-12-06 21:15 UTC, sen542 requested changes
Please see my comment in task #9.

2018-12-06 21:30 UTC, wzr1337 commented
**Token**

the additionalHeaders can not be included in the token:
1. The Auth Token is generated by an authority that does 'hopefully' does not know the X-Secret mentioned above
2. There might be other additional headers that must not or can not be known by the token issuer
3. the token is not necessary encrypted. I expect the JWT sent along to be signed, but not encrypted

**Intention:**
A request might need additional information that are NOT part of the object definition, such as a Secret code, so it can not be sent with the body payload with POST, even worse with GET and DELETE, were we do not have a body. I expect only transient information to be sent this way, so they do not pollute the payload.

2018-12-06 21:43 UTC, fibric commented
`X-<Something>` is typical for non-standard HTTP headers.
A use case on our side is to identify health issues in production where its value is also encrypted via `BASE64=SECRET+VALUE`.
A set of requests is marked explicitly to trigger verbose and extensive logging.
We are not using RSI, but we use `X-<Something>` headers because we don't need to mutate or manipulate the payload.

Another but wrong use-case is to use `X-<Something>` headers to authenticate a developer and circumvent certificate handling - a poor-man's authentification utility.

2018-12-15 17:13 UTC, sen542 commented
wzr1337 explanation from December 6th is not bad but it lacks a convincing part. You would never transmit an X-Secret header unencrpyted, wouldn't you? OK, for that you need encryption facilities. Having them on hand enables you to encrypt all these things in an access token. 
May be it is easier for me to follow your intention if you adapt the example.

2018-12-16 17:27 UTC, wzr1337 commented
@sen542 it is meant for things you would NOT put in a token. A token may carry scopes etc. But It may not be encrypted,just signed.. 

Think of the additional headers in terms of out of band pairing maybe.. you got all scopes, you are a valid user etc. But in order to pair with a device you need a code printed on a screen, or sent via SMS etc. 

Think also of a remote control maneuver for a car, e.g. parking. You might have a requirement where for legal reasons you need to enter a pin on an external device to drive the car. This pin would fit only into this header, as it is transient, maybe even random per maneuver but at least not suitable for being carried with a token that is sent to different services..

2018-12-16 20:22 UTC, sen542 commented
Thanks. Now it is understood. You might need to answer equal questions in the future...

2018-12-16 20:22 UTC, sen542 approved these changes

2018-12-18 07:51 UTC, merged